"""
IASW - Agent 4: Summary Agent
---------------------------------------------------------------------
Responsibility:
  * Generate a concise, human-readable natural language summary of the
    AI verification findings for the Checker Supervisor
  * Produce a recommended action (approve | review | reject)

Iteration strategy:
  - Exponential-backoff retry on transient Azure OpenAI errors (up to 2 attempts).
  - The deterministic fallback template is ONLY used if all retry attempts fail.
  - The recommendation is ALWAYS rule-based Python — never from the LLM.

Why less aggressive retry than Agent 2 (3 vs 2 attempts):
  - We already have a high-quality deterministic fallback.
  - This is a summary-generation step, not data extraction.
    A slight delay here is less critical than in the OCR step.

Why the recommendation is NEVER generated by the LLM:
  - Deterministic and auditable: same confidence score always → same recommendation.
  - A regulator can inspect the exact rule. An LLM recommendation cannot be audited.
"""
import asyncio

from openai import AzureOpenAI, RateLimitError, APIStatusError, APIConnectionError

from agents.state import PipelineState
from config import (
    AZURE_OPENAI_API_KEY,
    AZURE_OPENAI_ENDPOINT,
    AZURE_OPENAI_DEPLOYMENT,
    AZURE_OPENAI_API_VERSION,
    CONFIDENCE_FLAG_THRESHOLD,
    CONFIDENCE_REJECT_THRESHOLD,
)
from observability import AgentLogger

AGENT_NAME = "SummaryAgent"

# ── Retry configuration ───────────────────────────────────────────────────────
MAX_SUMMARY_RETRIES  = 2       # fewer than Agent 2 — we have a good fallback
RETRY_BASE_DELAY     = 2.0     # seconds — doubles each retry (2 → 4)

SUMMARY_SYSTEM = """
You are an AI verification assistant for a bank's account servicing team.
Write clear, factual, professional summaries for human Checker Supervisors.
Keep summaries concise (3-5 sentences). Use banking language.
Always end with a clear recommended action statement.
"""


def _get_azure_client() -> AzureOpenAI:
    return AzureOpenAI(
        api_key=AZURE_OPENAI_API_KEY,
        azure_endpoint=AZURE_OPENAI_ENDPOINT,
        api_version=AZURE_OPENAI_API_VERSION,
    )


def _is_transient_error(exc: Exception) -> bool:
    if isinstance(exc, RateLimitError):
        return True
    if isinstance(exc, APIStatusError) and exc.status_code >= 500:
        return True
    if isinstance(exc, APIConnectionError):
        return True
    return False


def _determine_recommendation(state: PipelineState) -> str:
    """
    Rule-based recommendation — deterministic and fully auditable.
    This is NEVER delegated to the LLM.

    Rules:
      forgery detected          → reject  (hard rule, no score overrides this)
      overall_confidence ≥ 0.70 → approve
      overall_confidence ≥ 0.40 → review
      overall_confidence < 0.40 → reject
    """
    if state.forgery_detected:
        return "reject"
    if state.overall_confidence >= CONFIDENCE_FLAG_THRESHOLD:
        return "approve"
    if state.overall_confidence >= CONFIDENCE_REJECT_THRESHOLD:
        return "review"
    return "reject"


def _build_fallback_summary(state: PipelineState) -> str:
    """Deterministic summary — used when all LLM attempts fail."""
    confidence_pct = round(state.overall_confidence * 100, 1)
    action_label = {
        "approve": "Recommend APPROVAL",
        "review":  "Recommend MANUAL REVIEW",
        "reject":  "Recommend REJECTION",
    }.get(state.recommended_action, "Recommend REVIEW")

    forgery_note = (
        f"Forgery indicators detected: {state.forgery_details}. "
        if state.forgery_detected else ""
    )
    scores_str = ", ".join(
        f"{k.replace('_', ' ').title()}: {round(v * 100, 1)}%"
        for k, v in state.confidence_scores.items()
    )

    return (
        f"AI verification completed for "
        f"{state.change_type.replace('_', ' ').title()} change request "
        f"for Customer {state.customer_id}. "
        f"Document analysis yielded an overall confidence score of {confidence_pct}%. "
        f"{forgery_note}"
        f"Field scores — {scores_str}. "
        f"FileNet reference: {state.filenet_reference_id}. {action_label}."
    )


async def run(state: PipelineState, logger: AgentLogger) -> PipelineState:
    """
    Generates a human-readable verification summary and recommendation.

    Flow:
      1. Compute recommendation deterministically (rule-based, always runs first)
      2. Try LLM summary with retry (up to MAX_SUMMARY_RETRIES attempts)
      3. On all LLM failures → use deterministic fallback summary
      4. Pipeline always completes — never fails at this step
    """
    logger.step_start(AGENT_NAME)

    # Step 1: Deterministic recommendation — computed BEFORE any LLM call
    state.recommended_action = _determine_recommendation(state)
    logger.info(
        AGENT_NAME, "recommendation_determined",
        recommendation=state.recommended_action,
        overall_confidence=state.overall_confidence,
        forgery_detected=state.forgery_detected,
    )

    # Build prompt
    scores_str = "\n".join(
        f"  - {field.replace('_', ' ').title()}: {round(score * 100, 1)}%"
        for field, score in state.confidence_scores.items()
    )
    forgery_note = (
        f"FORGERY INDICATORS DETECTED: {state.forgery_details}"
        if state.forgery_detected
        else "No forgery indicators detected."
    )
    extracted_str = "\n".join(
        f"  - {k.replace('_', ' ').title()}: {v}"
        for k, v in state.extracted_fields.items()
        if v and v != "None"
    )
    prompt = f"""
Generate a Checker Review Summary for the following account change request:

CHANGE REQUEST:
  - Customer ID: {state.customer_id}
  - Change Type: {state.change_type.replace('_', ' ').title()}
  - Current Value (RPS): {state.old_value}
  - Requested New Value: {state.new_value}

DOCUMENT ANALYSIS:
{extracted_str}

CONFIDENCE SCORES:
{scores_str}
  - OVERALL CONFIDENCE: {round(state.overall_confidence * 100, 1)}%

FORGERY CHECK: {forgery_note}

FILENET REFERENCE: {state.filenet_reference_id}

RECOMMENDED ACTION: {state.recommended_action.upper()}

Write a 3-5 sentence summary that a Checker Supervisor can use to make their decision.
Start with the document type verified, mention key field matches and confidence levels,
note any concerns, and end with the recommendation.
"""

    # Step 2: LLM call with exponential-backoff retry
    client = _get_azure_client()
    llm_succeeded = False

    for attempt in range(1, MAX_SUMMARY_RETRIES + 1):
        try:
            response = client.chat.completions.create(
                model=AZURE_OPENAI_DEPLOYMENT,
                max_tokens=512,
                messages=[
                    {"role": "system", "content": SUMMARY_SYSTEM},
                    {"role": "user",   "content": prompt},
                ],
            )
            state.ai_summary = response.choices[0].message.content.strip()
            llm_succeeded = True

            if attempt > 1:
                logger.info(AGENT_NAME, "summary_llm_retry_succeeded", attempt=attempt)
            break

        except Exception as exc:
            if not _is_transient_error(exc):
                # Permanent error — no retry, go straight to fallback
                logger.warning(
                    AGENT_NAME, "summary_llm_permanent_error_using_fallback",
                    error=str(exc), error_type=type(exc).__name__,
                )
                break

            if attempt < MAX_SUMMARY_RETRIES:
                delay = RETRY_BASE_DELAY * (2 ** (attempt - 1))
                logger.warning(
                    AGENT_NAME, "summary_llm_transient_error_retrying",
                    attempt=attempt,
                    max_attempts=MAX_SUMMARY_RETRIES,
                    retry_in_seconds=delay,
                    error=str(exc),
                )
                await asyncio.sleep(delay)
            else:
                logger.warning(
                    AGENT_NAME, "summary_llm_all_retries_exhausted_using_fallback",
                    attempts=MAX_SUMMARY_RETRIES,
                    error=str(exc),
                )

    # Step 3: Fallback if LLM failed
    if not llm_succeeded:
        state.ai_summary = _build_fallback_summary(state)
        logger.info(AGENT_NAME, "summary_fallback_used")

    logger.step_end(
        AGENT_NAME,
        result={
            "recommended_action": state.recommended_action,
            "summary_source": "llm" if llm_succeeded else "fallback",
            "summary_length": len(state.ai_summary),
        },
    )
    state.completed = True
    return state
